Do not attempt to decode LP_UNUSED line pointers
We previously called FormatItem on each item even when it was LP_UNUSED.
On x86_64, that was not a problem since the items seen in the test suite
had lp_len == 0, but on big-endian s390x, there are items with a
non-zero length and the decoder would complain about garbage.

"Good" case:

 Item   1 -- Length:    0  Offset:  773 (0x0305)  Flags: UNUSED
 Item   2 -- Length:    0  Offset:    0 (0x0000)  Flags: UNUSED

"Bad" case:

 Item   1 -- Length:    0  Offset:    0 (0x0000)  Flags: UNUSED
 Item   2 -- Length:  758  Offset:    0 (0x0000)  Flags: UNUSED
  Block Id: 0  linp Index: 402  Size: 7936
  Has Nulls: 1  Has Varwidths: 1

  Error: Index item size difference. Given <758>, Internal <7936>.