Use sizeof(PageHeaderData) in place of pageHeaderSize
With -Werror=vla, gcc complains about the localCache declaration.
Instead of the pageHeaderSize variable, use sizeof(PageHeaderData)
directly like elsewhere in this file.

pg_filedump.c:648:2: error: ISO C90 forbids array ‘localCache’ whose
size can’t be evaluated [-Werror=vla]